"""Add uploaded_at to Resource

Revision ID: 51c44fb66fd4
Revises: bb7ae1a6251f
Create Date: 2024-12-30 02:46:45.081246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c44fb66fd4'
down_revision = 'bb7ae1a6251f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'uploaded_at')
    # ### end Alembic commands ###
